# Generated by Django 6.0.2 on 2026-08-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audit', models.DateTimeField(auto_now_add=True)),
                ('fichier_nom', models.CharField(max_length=255)),
                ('total_anomalies', models.IntegerField(default=0)),
                ('montant_risque', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DossierClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('siren', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('ELEVE', 'Élevé'), ('MOYEN', 'Moyen')], max_length=20)),
                ('type_anomalie', models.CharField(max_length=255)),
                ('date_ecriture', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=50, null=True)),
                ('piece', models.CharField(blank=True, max_length=100, null=True)),
                ('compte', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='api.auditfec')),
            ],
        ),
        migrations.AddField(
            model_name='auditfec',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.dossierclient'),
        ),
    ]
