# Generated by Django 6.0.2 on 2026-08-11 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalie',
            options={'verbose_name': 'Anomalie', 'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterModelOptions(
            name='auditfec',
            options={'verbose_name': 'Audit FEC', 'verbose_name_plural': 'Audits FEC'},
        ),
        migrations.AlterModelOptions(
            name='dossierclient',
            options={'verbose_name': 'Dossier Client', 'verbose_name_plural': 'Dossiers Clients'},
        ),
        migrations.AddField(
            model_name='auditfec',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_effectues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='compte',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='gravite',
            field=models.CharField(choices=[('CRITIQUE', 'Critique'), ('HAUTE', 'Haute'), ('ELEVE', 'Élevé'), ('MOYEN', 'Moyen')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierclient',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='dossierclient',
            name='siren',
            field=models.CharField(db_index=True, default=1, max_length=9, verbose_name='Numéro SIREN'),
            preserve_default=False,
        ),
    ]
