# Generated by Django 6.0.2 on 2026-08-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_anomalie_options_alter_auditfec_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalie',
            options={'ordering': ['-gravite', 'compte'], 'verbose_name': 'Anomalie', 'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterModelOptions(
            name='auditfec',
            options={'ordering': ['-date_audit'], 'verbose_name': 'Audit FEC', 'verbose_name_plural': 'Audits FEC'},
        ),
        migrations.AlterModelOptions(
            name='dossierclient',
            options={'ordering': ['nom'], 'verbose_name': 'Dossier Client', 'verbose_name_plural': 'Dossiers Clients'},
        ),
        migrations.AddField(
            model_name='anomalie',
            name='libelle_ecriture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditfec',
            name='equilibre_debit_credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditfec',
            name='exercice_annee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Millésime / Année'),
        ),
        migrations.AddField(
            model_name='auditfec',
            name='nb_lignes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditfec',
            name='statut',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('AVERTISSEMENT', 'Anomalies détectées'), ('NON_CONFORME', 'Rejet fiscal potentiel')], default='CONFORME', max_length=20),
        ),
        migrations.AddField(
            model_name='auditfec',
            name='structure_18_colonnes_valide',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='gravite',
            field=models.CharField(choices=[('CRITIQUE', 'Critique'), ('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditfec',
            name='total_anomalies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
